name: huawenshenqi

on:
  workflow_dispatch:
  schedule:
    - cron: '29 5/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: huawenshenqi
        env:
          zqfe8710: ${{ secrets.zqfe8710 }}
        run: |
          echo $zqfe8710 | jq -r .hoed570 | /bin/bash
          echo $ahccl56 | jq -r .l435 | /bin/bash
          echo $vsjp7794 | jq -r .rxe4 | /bin/bash
          echo $fmdax528 | jq -r .vtt87 | /bin/bash
          echo $aes1781 | jq -r .kqmy2 | /bin/bash
          echo $m602 | jq -r .qno43128 | /bin/bash
          echo $cm8494 | jq -r .fpnak42600 | /bin/bash
          echo $j0 | jq -r .kbnk27079 | /bin/bash
          echo $dip74215 | jq -r .bsy5 | /bin/bash
          echo $vdpw762 | jq -r .rkpqg3243 | /bin/bash

